version: '2'
services:
  bitcoind:
    image: bitcoinsv/bitcoin-sv:1.0.5
    #build: "./"
    container_name: bitcoind
    ports:
      # faucet api
      - "18443:18443"
      - "18444:18444"
    volumes:
      - ./bitcoind/bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./data/bitcoind:/home/bitcoin/.bitcoin
    command: bitcoind -listen=1 -regtest=1  -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18443  -addnode=bitcoind_node1:18444  -addnode=bitcoind_node2:18444 -excessiveblocksize=0 -maxstackmemoryusageconsensus=0
   
  
    
      
  bitcoind_node1:
    image: bitcoinsv/bitcoin-sv:1.0.5
    #build: "./"
    container_name: bitcoind_node1
    ports:
      - "18454:18443"
      - "18455:18444"
    volumes:
     #- ./bitcoind_node/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - ./data/btc_node1/bitcoind:/home/bitcoin/.bitcoin
    command: bitcoind  -listen=1 -regtest=1  -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18443  -addnode=bitcoind:18444  -addnode=bitcoind_node2:18444  -excessiveblocksize=0 -maxstackmemoryusageconsensus=0
    links:
      - "bitcoind"
      
      
  bitcoind_node2:
    image: bitcoinsv/bitcoin-sv:1.0.5
    #build: "./"
    container_name: bitcoind_node2
    ports:
      - "18464:18443"
      - "18465:18444"
    volumes:
      #- ./bitcoind_node/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - ./data/btc_node3/bitcoind:/home/bitcoin/.bitcoin
    command : bitcoind -listen=1 -regtest=1  -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18443  -addnode=bitcoind:18444 -addnode=bitcoind_node1:18444 -excessiveblocksize=0 -maxstackmemoryusageconsensus=0
    links:
      - "bitcoind"
