version: '2'
services:
  bitcoind:
    image: debian:stretch-slim 
    #build: "./"
    container_name: bitcoind
    ports:
      # faucet api
      - "3001:3000"
      - "18332:18332"
      - "18333:18333"
      - "18443:18443"
      - "18444:18444"
    expose:
      # rpc api
      - "18443"
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./data/bitcoind:/home/bitcoin/.bitcoin
  
    
      
  bitcoind_node1:
    image: debian:stretch-slim 
    #build: "./"
    container_name: bitcoind_node1
    ports:
      # faucet api
      - "3021:3000"
      - "18352:18332"
      - "18353:18333"
      - "18454:18443"
      - "18455:18444"
    expose:
      # rpc api
      - "18454"
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./data/btc_node1/bitcoind:/home/bitcoin/.bitcoin
    links:
      - "bitcoind"
      
      
  bitcoind_node2:
    image:  debian:stretch-slim 
    #build: "./"
    container_name: bitcoind_node2
    ports:
      # faucet api
      - "3031:3000"
      - "18362:18332"
      - "18363:18333"
      - "18464:18443"
      - "18465:18444"
    expose:
      # rpc api
      - "18464"
    volumes:
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./data/btc_node2/bitcoind:/home/bitcoin/.bitcoin
    links:
      - "bitcoind"
