version: '2'
services:
  bitcoind:
    image: Roberrtt/robert
    #build: "./BU"
    container_name: bitcoind
    ports:
      # faucet api
      - "3001:3000"
      - "18332:18332"
      - "18333:18333"
      - "18443:18443"
      - "18444:18444"
    expose:
      # rpc api
      - "18443"
    command: -printtoconsole  -listen=1 -regtest=1  -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18443  -addnode=bitcoind_node1:18444  -addnode=bitcoind_node2:18444 -minrelaytxfee=1231321
    volumes:
      - ./BU/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - ./data/bitcoind:/home/bitcoin/.bitcoin
  
    
      
  bitcoind_node1:
    image: Roberrtt/robert
    #build: "./BU"
    container_name: bitcoind_node1
    ports:
      # faucet api
      - "3021:3000"
      - "18352:18332"
      - "18353:18333"
      - "18454:18443"
      - "18455:18444"
    expose:
      # rpc api
      - "18454"
    volumes:
      - ./BU/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - ./data/btc_node1/bitcoind:/home/bitcoin/.bitcoin
    command: -printtoconsole  -listen=1 -regtest=1  -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18444  -addnode=bitcoind:18444  -addnode=bitcoind_node2:18444 -addnode=bitcoind_node3:18444 -addnode=bitcoind_node4:18444 -addnode=bitcoind_node5:18444 -addnode=bitcoind_node6:18444
    links:
      - "bitcoind"
  bitcoind_node2:
    image:  Roberrtt/robert
    #build: "./BU"
    container_name: bitcoind_node2
    ports:
      # faucet api
      - "3031:3000"
      - "18362:18332"
      - "18363:18333"
      - "18464:18443"
      - "18465:18444"
    expose:
      # rpc api
      - "18464"
    volumes:
      - ./BU/bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf
      - ./data/btc_node2/bitcoind:/home/bitcoin/.bitcoin
    command: -printtoconsole  -listen=1 -regtest=1  -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18444  -addnode=bitcoind:18444 -addnode=bitcoind_node1:18444 -addnode=bitcoind_node3:18444 -addnode=bitcoind_node4:18444 -addnode=bitcoind_node5:18444 -addnode=bitcoind_node6:18444
    links:
      - "bitcoind"
