version: '3'
services:
  bitcoind:
    #image: uphold/bitcoin-abc:0.21.12
    build: ./
    container_name: bitcoind
    # specify additional command line arguments here
    command: bitcoind -printtoconsole -regtest=1 -listen=1 -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18443 -port=18444 -addnode=bitcoind1:18444 -addnode=bitcoind2:18444 -rpcbind=0.0.0.0 
    ports:
      - "18444:18444"
      - "18443:18443"
    volumes:
      # using a custom path for data dir
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./data:/data
    
  
  bitcoind1:
   # image: uphold/bitcoin-abc:0.21.12
    build: ./
    container_name: bitcoind1
    command: bitcoind -printtoconsole -regtest=1 -listen=1 -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18443 -port=18444 -addnode=bitcoind:18444 -addnode=bitcoind2:18444 -rpcbind=0.0.0.0
    ports:
      - "18445:18444"
      - "18453:18443"
    volumes:
      - ./data/bitcoind1:/data
    links: 
      - "bitcoind"
          
  bitcoind2:
    #image: uphold/bitcoin-abc:0.21.12
    build: ./
    container_name: bitcoind2
    command: bitcoind -printtoconsole -regtest=1 -listen=1 -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18443 -port=18444 -addnode=bitcoind:18444 -addnode=bitcoind1:18444 -rpcbind=0.0.0.0
    ports:
      - "18455:18444"
      - "18463:18443"
    volumes:
      - ./data/bitcoind2:/data
    links:
      - "bitcoind"
      
  electrumx:
    image: lukechilds/electrumx
    depends_on:
      - "bitcoind"
    ports:
      - "55002:50002"
      - "55001:50001"
    volumes:
      - ./data/electrumx:/data
    environment:
      - DAEMON_URL=http://electrum:electrum@bitcoind:18443
      - COIN=BitcoinCashABC
      - NET=regtest
      - ALLOW_ROOT=1
    links:
      - "bitcoind"
