version: '2'
services:
  bitcoind:
    image: slashrsm/bitcoin-cash-regtest
    #build: "./bitcoind"
    container_name:  bitcoind
    ports:
      # faucet api
      - "18343:18332"
      - "18333:18333"
    expose:
      - "18343"
      - "18333"
    volumes:
      #- /opt/bitcoin/bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./data/bitcoind:/root/.bitcoin/
    command: bitcoind -printtoconsole  -listen=1 -regtest=1 -port=18333 -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18332 -addnode=bitcoind_node1:18333 -addnode=bitcoind_node2:18333 


  bitcoind_node1:
    image:  slashrsm/bitcoin-cash-regtest
    #build: "./bitcoind_node"
    container_name:  bitcoind_node1
    ports:
      # faucet api
      - "18454:18332"
      - "18453:18333"
    expose:
      - "18454"
      - "18333"
    volumes:
      #- /opt/bitcoin/bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./data/btc_node1:/root/.bitcoin/
    command: bitcoind -printtoconsole  -listen=1 -regtest=1 -port=18333 -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18332 -addnode=bitcoind:18333 -addnode=bitcoind_node2:18333 
    links:
      - "bitcoind"
      
      
  bitcoind_node2:
     image:  slashrsm/bitcoin-cash-regtest
     #build: "./bitcoind_node"
     container_name:  bitcoind_node2
     ports:
      # faucet api
      - "18444:18332"
      - "18463:18333"
     expose:
      - "18464"
      - "18463"
     volumes:
      #- /opt/bitcoin/bitcoin.conf:/root/.bitcoin/bitcoin.conf
      - ./data/btc_node2:/root/.bitcoin/
     command: bitcoind -printtoconsole  -listen=1 -regtest=1 -port=18333 -rpcallowip=0.0.0.0/0 -rpcuser=electrum -rpcpassword=electrum  -rpcport=18332 addnode=bitcoind_node1:18333 -addnode=bitcoind:18333  
     links:
      - "bitcoind" 
